// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _sidebar_nav from './sidebar-nav.bones.json'
import _calendar from './calendar.bones.json'
import _chat from './chat.bones.json'
import _dashboard_stats from './dashboard-stats.bones.json'
import _chart_traffic from './chart-traffic.bones.json'
import _chart_deploys from './chart-deploys.bones.json'
import _chart_split from './chart-split.bones.json'
import _user_table from './user-table.bones.json'
import _activity from './activity.bones.json'
import _kanban from './kanban.bones.json'
import _files from './files.bones.json'
import _progress from './progress.bones.json'
import _servers from './servers.bones.json'

registerBones({
  "sidebar-nav": _sidebar_nav,
  "calendar": _calendar,
  "chat": _chat,
  "dashboard-stats": _dashboard_stats,
  "chart-traffic": _chart_traffic,
  "chart-deploys": _chart_deploys,
  "chart-split": _chart_split,
  "user-table": _user_table,
  "activity": _activity,
  "kanban": _kanban,
  "files": _files,
  "progress": _progress,
  "servers": _servers,
})
