// Regenerates lib/core/mock/mock_bundle_embedded.g.dart from assets/data/mock_bundle.json
// Run after editing the JSON: dart run tool/embed_mock_bundle.dart
import 'dart:convert';
import 'dart:io';

void main() {
  final file = File('assets/data/mock_bundle.json');
  if (!file.existsSync()) {
    stderr.writeln('Missing assets/data/mock_bundle.json');
    exitCode = 1;
    return;
  }
  final bytes = file.readAsBytesSync();
  final b64 = base64Encode(bytes);

  final sink = StringBuffer()
    ..writeln('// GENERATED by tool/embed_mock_bundle.dart — do not edit.')
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln(
      '/// Fallback when `rootBundle` has no manifest entry (common after hot restart',
    )
    ..writeln('/// before a full rebuild, or when assets are misconfigured).')
    ..writeln('String loadEmbeddedMockBundleJson() {')
    ..writeln('  const chunks = <String>[');

  const chunkSize = 72;
  for (var i = 0; i < b64.length; i += chunkSize) {
    final end = i + chunkSize > b64.length ? b64.length : i + chunkSize;
    sink.writeln("    '${b64.substring(i, end)}',");
  }
  sink.writeln('  ];');
  sink.writeln('  return utf8.decode(base64Decode(chunks.join()));');
  sink.writeln('}');

  File(
    'lib/core/mock/mock_bundle_embedded.g.dart',
  ).writeAsStringSync(sink.toString());
  // ignore: avoid_print
  print(
    'Wrote lib/core/mock/mock_bundle_embedded.g.dart (${bytes.length} bytes)',
  );
}
